title: picoTracker User Manual
author: xiphonics

styles:
  code:
    background-color: 0x9999FF
  show-page-numbers-from: 1
  # path from inside assets dir
  ttf-font-path: fonts/Exo2-Regular.ttf

tocPagePosition: 1

pages:
  - cover.md
  - index.md
  - 2ndpage.md
