name: picosite
description: A minimal static site generator with http preview server
version: 0.2.0
repository: https://github.com/maks/picosite

environment:
  sdk: ^3.4.4

dependencies:
  args: ^2.4.2
  io: ^1.0.4
  markdown: ^7.2.2
  mustache_template: ^2.0.0
  path: ^1.9.0
  shelf: ^1.4.2
  shelf_static: ^1.1.2
  watcher: ^1.1.0
  yaml: ^3.1.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0

executables:
  picosite:
