name: picosite
description: A minimal static site generator with http preview server
version: 0.0.1
repository: https://github.com/maks/picosite

environment:
  sdk: ^3.4.4

dependencies:
  args: ^2.4.2
  io: any
  markdown: any
  mustache_template: ^2.0.0
  path: any
  shelf: any
  shelf_static: any
  watcher:  any
  yaml: ^3.1.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0

executables:
  picosite:
