name: picosite
description: A minimal static site generator with http preview server
version: 0.0.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.4.4

# Add regular dependencies here.
dependencies:
  args: ^2.4.2
  markdown: any
  path: any
  shelf: any
  shelf_static: any
  yaml: ^3.1.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0

executables:
  picosite:
