import 'dart:io';

/// Reads the version from pubspec.yaml and writes it into lib/version.dart.
/// Paths are resolved relative to the project root (parent of this script's dir).
void main(List<String> arguments) {
  // Resolve paths relative to the project root, not cwd.
  final scriptDir = Directory.fromUri(Platform.script);
  final projectRoot = scriptDir.parent.path;

  final pubspecFile = File('$projectRoot/pubspec.yaml');
  if (!pubspecFile.existsSync()) {
    print('ERROR: pubspec.yaml not found at ${pubspecFile.path}');
    exit(1);
  }

  final pubspecContent = pubspecFile.readAsStringSync();
  // Match version: X.Y.Z optionally followed by -pre, +build etc.
  final versionRegex = RegExp(r'^version:\s*([\d]+\.[\d]+\.[\d]+(?:-[\w.]+)?)', multiLine: true);
  final match = versionRegex.firstMatch(pubspecContent);

  if (match != null) {
    final version = match.group(1)!;
    print('Version from pubspec.yaml: $version');

    final output = File('$projectRoot/lib/version.dart');
    output.writeAsStringSync(
      '// This file is automatically generated by tools/setversion.dart.\n'
      '// Do not edit manually — update version in pubspec.yaml instead.\n'
      "const String version = '$version';\n",
    );
    print('Wrote version to ${output.path}');
  } else {
    print('ERROR: Could not find version in pubspec.yaml');
    exit(1);
  }
}
