name: Build on Push

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        include:
          - os: ubuntu-latest
            output-name: picosite-linux
          - os: macOS-latest
            output-name: picosite-mac
          - os: windows-latest
            output-name: picosite-windows.exe

    steps:
      - uses: actions/checkout@v1
      - uses: DanTup/gh-actions/setup-dart@master
      - run: mkdir output
      - run: dart pub get
      - run: dart compile exe bin/picosite.dart -v -o output/${{ matrix.output-name }}
      - uses: actions/upload-artifact@v3
        with:
          name: native-executables
          path: output